services:
  web:
    build:
      dockerfile: ./src/dockerfile
    environment:
      POSTGRRES_DB: "testdb"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "12340:12340"
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "server.py"]

  db:
    image: postgres:14.8-alpine3.18
    restart: always
    environment:
      POSTGRRES_DB: "testdb"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5430:5432"
