services:
  web:
    build:
      context: ./src
      dockerfile: dockerfile
    environment:
      SHA256_SECRET_KEY: 'dsgfgfdgsd'
      SECRET_ADMINISTRATOR: "jfgjjhbjbbjkb"
      SECRET_USER: "jfgjjhbjbbjkb"
      POSTGRES_DB: "db_cvs5"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "5qJZDWLLNlHFEdR56rn8mJRg03sno3V1"
      POSTGRES_HOST: "dpg-cueg6thu0jms73caudl0-a.oregon-postgres.render.com"
      POSTGRES_PORT: "5432"
      SALT: 'dsngbdjkfmld;'
    ports:
      - "12340:12340"
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "server.py"]

  db:
    image: postgres:14.8-alpine3.18
    restart: always
    environment:
      POSTGRRES_DB: "testdb"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5430:5432"
